version: "3.1"

services:

  kea-dhcp4:
    image: tmuncks/kea-dhcp4:latest
    restart: always
    command: /usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4.conf
    ports:
      - "67:67/udp"
    tmpfs:
      # prevent hang after crash, when lock files have not been cleaned up
      - /run/kea 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/kea:/etc/kea:ro
      - data:/var/kea

volumes:
  data:
